<?php 
// Particles Background Element

vc_map( array(
            "name" => esc_html__("Particles Background", 'tba-particles'),
            "description" => esc_html__("Add Particles to Background", 'tba-particles'),
            "base" => "tba_particles_background",
            "class" => "",
            "controls" => "full",
            "params" => array(
              array("save_always" => true, "type" => "textfield", "holder" => "div", "class" => "", "heading" => esc_html__("Id - unique per page", "tba-particles"), "param_name" => "theid", "value" => "_".time()."_".rand(100000,999999999) ),
              array("save_always" => true, "type" => "textfield",  "class" => "", "heading" => esc_html__("Particles number", "tba-particles"), "param_name" => "particles_number_value", "value" => "80", "description" => "Integer (0-1000)." ),
              array("save_always" => true, "type" => "textfield",  "class" => "", "heading" => esc_html__("Particles density", "tba-particles"), "param_name" => "particles_density_value", "value" => "800", "description" => "Integer (0-1000). Use this value instead of particles number to avoid scaling issues on mobile." ),
              array("save_always" => true, "type" => "dropdown",  "class" => "", "heading" => esc_html__("Particle type", "tba-particles"), "param_name" => "particles_shape_type", "value" => array("Circle","Image","Polygon","Star"), "description" => "" ),
              array("save_always" => true, "dependency" => array("element" => "particles_shape_type", "value" => array("Image")), "type" => "attach_image",  "class" => "", "heading" => esc_html__("Particle image", "tba-particles"), "param_name" => "particles_shape_image_src", "value" => "", "description" => "For image particle type only!" ),
              array("save_always" => true, "dependency" => array("element" => "particles_shape_type", "value" => array("Circle","Polygon","Star")), "type" => "colorpicker",  "class" => "", "heading" => esc_html__("Particle color", "tba-particles"), "param_name" => "particles_color", "value" => "000000", "description" => "Not for image particle type!" ),
              array("save_always" => true, "dependency" => array("element" => "particles_shape_type", "value" => array("Circle","Polygon","Star")), "type" => "colorpicker",  "class" => "", "heading" => esc_html__("Particle stroke color", "tba-particles"), "param_name" => "particles_shape_stroke_color", "value" => "000000", "description" => "Not for image particle type!" ),
              array("save_always" => true, "dependency" => array("element" => "particles_shape_type", "value" => array("Circle","Polygon","Star")), "type" => "textfield",  "class" => "", "heading" => esc_html__("Particle stroke width", "tba-particles"), "param_name" => "particles_shape_stroke_width", "value" => "0", "description" => "Not for image particle type! Integer (0-20)" ),
              array("save_always" => true, "dependency" => array("element" => "particles_shape_type", "value" => array("Polygon")), "type" => "textfield",  "class" => "", "heading" => esc_html__("Polygon particle sides", "tba-particles"), "param_name" => "particles_shape_polygon_nb_sides", "value" => "5", "description" => "For polygon particle type only! Integer (3-20)" )
            )
        ) );

        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "textfield",  "group" => "Sizing", "class" => "", "heading" => esc_html__("Particle size", "tba-particles"), "param_name" => "particles_size_value", "value" => "5", "description" => "Integer (0-500)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "dropdown",  "group" => "Sizing", "class" => "", "heading" => esc_html__("Randomize particle size", "tba-particles"), "param_name" => "particles_size_random", "value" => array("Yes" => "true", "No" => "false")));
        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "dropdown",  "group" => "Sizing", "class" => "", "heading" => esc_html__("Animate particle size", "tba-particles"), "param_name" => "particles_size_anim_enable", "value" =>  array("No" => "false", "Yes" => "true") ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_size_anim_enable", "value" => array("true")), "type" => "textfield",  "group" => "Sizing", "class" => "", "heading" => esc_html__("Animation speed", "tba-particles"), "param_name" => "particles_size_anim_speed", "value" => "40", "description" => "Integer (0-300)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_size_anim_enable", "value" => array("true")), "type" => "textfield",  "group" => "Sizing", "class" => "", "heading" => esc_html__("Minimum particle size", "tba-particles"), "param_name" => "particles_size_anim_size_min", "value" => "0.1", "description" => "Float ( > 0.1)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_size_anim_enable", "value" => array("true")), "type" => "dropdown",  "group" => "Sizing", "class" => "", "heading" => esc_html__("Sync animation", "tba-particles"), "param_name" => "particles_size_anim_sync", "value" => array("No" => "false", "Yes" => "true") ));

        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "textfield",  "group" => "Opacity", "class" => "", "heading" => esc_html__("Particle opacity", "tba-particles"), "param_name" => "particles_opacity_value", "value" => "0.5", "description" => "Float (0.00 - 1.00)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "dropdown",  "group" => "Opacity", "class" => "", "heading" => esc_html__("Randomize opacity", "tba-particles"), "param_name" => "particles_opacity_random", "value" => array("Yes" => "true", "No" => "false") ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "dropdown",  "group" => "Opacity", "class" => "", "heading" => esc_html__("Animate particle opacity", "tba-particles"), "param_name" => "particles_opacity_anim_enable", "value" => array("No" => "false", "Yes" => "true") ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_opacity_anim_enable", "value" => array("true")), "type" => "textfield",  "group" => "Opacity", "class" => "", "heading" => esc_html__("Animation speed", "tba-particles"), "param_name" => "particles_opacity_anim_speed", "value" => "1", "description" => "Integer (0-10)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_opacity_anim_enable", "value" => array("true")), "type" => "textfield",  "group" => "Opacity", "class" => "", "heading" => esc_html__("Minimum particle opacity", "tba-particles"), "param_name" => "particles_opacity_anim_opacity_min", "value" => "0.1", "description" => "Float (0.00 - 1.00)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_opacity_anim_enable", "value" => array("true")), "type" => "dropdown",  "group" => "Opacity", "class" => "", "heading" => esc_html__("Sync animation", "tba-particles"), "param_name" => "particles_opacity_anim_sync", "value" => array("No" => "false", "Yes" => "true") ));

        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "dropdown",  "group" => "Movement", "class" => "", "heading" => esc_html__("Enable movement", "tba-particles"), "param_name" => "particles_move_enabled", "value" => array("Yes" => "true", "No" => "false"), "description" => "" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_move_enabled", "value" => array("true")), "type" => "dropdown",  "group" => "Movement", "class" => "", "heading" => esc_html__("Direction", "tba-particles"), "param_name" => "particles_move_direction", "value" => array("none","top","top-right","right","bottom-right","bottom","bottom-left","left","top-left"), "description" => "" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_move_enabled", "value" => array("true")), "type" => "dropdown",  "group" => "Movement", "class" => "", "heading" => esc_html__("Enable random particles", "tba-particles"), "param_name" => "particles_move_random", "value" => array("No" => "false", "Yes" => "true"), "description" => "" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_move_enabled", "value" => array("true")), "type" => "dropdown",  "group" => "Movement", "class" => "", "heading" => esc_html__("Enable straight particles", "tba-particles"), "param_name" => "particles_move_straight", "value" => array("No" => "false", "Yes" => "true"), "description" => "" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_move_enabled", "value" => array("true")), "type" => "textfield",  "group" => "Movement", "class" => "", "heading" => esc_html__("Speed", "tba-particles"), "param_name" => "particles_move_speed", "value" => '6', "description" => "integer (0-200)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_move_enabled", "value" => array("true")), "type" => "dropdown",  "group" => "Movement", "class" => "", "heading" => esc_html__("Boundary mode", "tba-particles"), "param_name" => "particles_move_out_mode", "value" => array("bounce","out"), "description" => "" ));
        
        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "dropdown",  "group" => "Line linking", "class" => "", "heading" => esc_html__("Enable line linking", "tba-particles"), "param_name" => "particles_line_linked_enable_auto", "value" => array("Yes" => "true", "No" => "false"), "description" => "" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_line_linked_enable_auto", "value" => array("true")), "type" => "textfield",  "group" => "Line linking", "class" => "", "heading" => esc_html__("Maximum distance", "tba-particles"), "param_name" => "particles_line_linked_distance", "value" => "150", "description" => "Integer (0-500)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_line_linked_enable_auto", "value" => array("true")), "type" => "colorpicker",  "group" => "Line linking", "class" => "", "heading" => esc_html__("Line color", "tba-particles"), "param_name" => "particles_line_linked_color", "value" => "000000", "description" => "" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_line_linked_enable_auto", "value" => array("true")), "type" => "textfield",  "group" => "Line linking", "class" => "", "heading" => esc_html__("Line opacity", "tba-particles"), "param_name" => "particles_line_linked_opacity", "value" => "0.40", "description" => "Float (0.00 - 1.00)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_line_linked_enable_auto", "value" => array("true")), "type" => "textfield",  "group" => "Line linking", "class" => "", "heading" => esc_html__("Line width", "tba-particles"), "param_name" => "particles_line_linked_width", "value" => "1", "description" => "Integer (0-20)" ));
        
        
        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "dropdown",  "group" => "Interactivity", "class" => "", "heading" => esc_html__("Enable?", "tba-particles"), "param_name" => "particles_interactivity_onhover_enable", "value" => array("No" => "false", "Yes" => "true"), "description" => ""));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_interactivity_onhover_enable", "value" => array("true")), "type" => "dropdown",  "group" => "Interactivity", "class" => "", "heading" => esc_html__("Mode", "tba-particles"), "param_name" => "particles_interactivity_onhover_mode", "value" => array("grab","repulse"), "description" => "" ));
        
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_interactivity_onhover_mode", "value" => array("grab")), "type" => "textfield",  "group" => "Interactivity", "class" => "", "heading" => esc_html__("Grab distance", "tba-particles"), "param_name" => "particles_interactivity_modes_grab_distance", "value" => "312", "description" => "Integer (0-1500)" ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_interactivity_onhover_mode", "value" => array("grab")), "type" => "textfield",  "group" => "Interactivity", "class" => "", "heading" => esc_html__("Grab opacity", "tba-particles"), "param_name" => "particles_interactivity_modes_grab_line_linked_opacity", "value" => "0.7", "description" => "Float (0.00 - 1.00)" ));       
        vc_add_param("tba_particles_background", array( "save_always" => true, "dependency" => array("element" => "particles_interactivity_onhover_mode", "value" => array("repulse")), "type" => "textfield",  "group" => "Interactivity", "class" => "", "heading" => esc_html__("Repulse distance", "tba-particles"), "param_name" => "particles_interactivity_modes_repulse_distance", "value" => "312", "description" => "Integer (0-1500)" ));
        
        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "textfield",  "group" => "Compatibility", "class" => "", "heading" => esc_html__("VC Row hookup classes", "tba-particles"), "param_name" => "particles_compatibility_customclass", "value" => ".vc_vcrow, .vc_row, .wpb_row", "description" => "If your theme is using custom VC Row classes add custom class name." ));
        vc_add_param("tba_particles_background", array( "save_always" => true, "type" => "textfield",  "group" => "Compatibility", "class" => "", "heading" => esc_html__("Z-index", "tba-particles"), "param_name" => "particles_compatibility_zindex", "value" => "2", "description" => "Custom z-index. If there is problem first try: 3,1,0,-1" ));

?>